"""Writes codebook-refinement/v3/crosswalk-2.5.1-to-3.0.0.csv, the mechanical
old-to-new map (renumbering rule: generated by script, checked by a test).

It takes the approved map in docs/codebook/crosswalk-2.4.0-to-proposed.csv
(the code set did not change between 2.4.0 and 2.5.1) and fills in the full
3.0.0 code strings from codebooks/youthOutcomesV3.data.ts.

    python3 codebook-refinement/v3/build_crosswalk.py
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = (ROOT / 'codebooks/youthOutcomesV3.data.ts').read_text()
DOMAINS = json.loads(DATA[DATA.index('= [') + 2:DATA.rindex(';')])
NAME = {c['id']: f"{c['id']} {c['name']}" for d in DOMAINS for cat in d['categories'] for c in cat['codes']}

rows = list(csv.DictReader((ROOT / 'docs/codebook/crosswalk-2.4.0-to-proposed.csv').open()))
out = ROOT / 'codebook-refinement/v3/crosswalk-2.5.1-to-3.0.0.csv'
with out.open('w', newline='') as f:
    w = csv.writer(f, lineterminator='\n')
    w.writerow(['old_code', 'new_code', 'mapping', 're_review_targets'])
    for r in rows:
        mapping = 'split' if r['mapping'].startswith('split') else r['mapping']
        targets = [NAME[t] for t in re.findall(r'[YFA]\d+\.\d+', r['re_review_targets'])]
        w.writerow([r['old_label'], NAME[r['new_code']], mapping, ' | '.join(targets)])
print(f'wrote {out.relative_to(ROOT)}: {len(rows)} rows')
